FROM php:7.2-fpm-alpine3.7
RUN apk update && apk upgrade && \
 apk add --no-cache \
  postgresql-dev \
  g++ libtool make autoconf imagemagick imagemagick-dev && \
  pecl channel-update pecl.php.net && \
  pecl install imagick-beta && \
  docker-php-ext-enable imagick && \
  docker-php-ext-install pgsql pdo_pgsql

CMD ["./wait-for-setup.sh", "php-fpm"]
